runtime: python37
service: deepdrive-sim-service

# Basic scaling is necessary to allow the cron watchdog to run for up to 24h
# Otherwise, it will be capped at 1 min. This _should_ be fine, so we can change
# to automatic scaling once performance characteristics are known and we _need_
# to scale that much.
# c.f. https://cloud.google.com/tasks/docs/creating-appengine-handlers#timeouts
basic_scaling:
  max_instances: 25
  idle_timeout: 10m
